/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as O_nasRouteImport } from './routes/o_nas'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIdRouteImport } from './routes/books/$id'
import { Route as StaffReviewsRouteImport } from './routes/_staff/reviews'
import { Route as StaffReservationsRouteImport } from './routes/_staff/reservations'
import { Route as StaffPublishersRouteImport } from './routes/_staff/publishers'
import { Route as StaffNewsletterRouteImport } from './routes/_staff/newsletter'
import { Route as StaffNew_newsletterRouteImport } from './routes/_staff/new_newsletter'
import { Route as StaffGenresRouteImport } from './routes/_staff/genres'
import { Route as StaffFeedbacksRouteImport } from './routes/_staff/feedbacks'
import { Route as StaffBooks_admRouteImport } from './routes/_staff/books_adm'
import { Route as StaffAuthorsRouteImport } from './routes/_staff/authors'
import { Route as ProtectedWishlistRouteImport } from './routes/_protected/wishlist'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedMyReservationsRouteImport } from './routes/_protected/my-reservations'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as StaffReviewsIdRouteImport } from './routes/_staff/reviews/$id'

const O_nasRoute = O_nasRouteImport.update({
  id: '/o_nas',
  path: '/o_nas',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReviewsRoute = StaffReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => StaffRoute,
} as any)
const StaffReservationsRoute = StaffReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPublishersRoute = StaffPublishersRouteImport.update({
  id: '/publishers',
  path: '/publishers',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNewsletterRoute = StaffNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNew_newsletterRoute = StaffNew_newsletterRouteImport.update({
  id: '/new_newsletter',
  path: '/new_newsletter',
  getParentRoute: () => StaffRoute,
} as any)
const StaffGenresRoute = StaffGenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFeedbacksRoute = StaffFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBooks_admRoute = StaffBooks_admRouteImport.update({
  id: '/books_adm',
  path: '/books_adm',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAuthorsRoute = StaffAuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => StaffRoute,
} as any)
const ProtectedWishlistRoute = ProtectedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyReservationsRoute = ProtectedMyReservationsRouteImport.update({
  id: '/my-reservations',
  path: '/my-reservations',
  getParentRoute: () => ProtectedRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const StaffReviewsIdRoute = StaffReviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffReviewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/o_nas': typeof O_nasRoute
  '/users': typeof AdminUsersRoute
  '/my-reservations': typeof ProtectedMyReservationsRoute
  '/profile': typeof ProtectedProfileRoute
  '/wishlist': typeof ProtectedWishlistRoute
  '/authors': typeof StaffAuthorsRoute
  '/books_adm': typeof StaffBooks_admRoute
  '/feedbacks': typeof StaffFeedbacksRoute
  '/genres': typeof StaffGenresRoute
  '/new_newsletter': typeof StaffNew_newsletterRoute
  '/newsletter': typeof StaffNewsletterRoute
  '/publishers': typeof StaffPublishersRoute
  '/reservations': typeof StaffReservationsRoute
  '/reviews': typeof StaffReviewsRouteWithChildren
  '/books/$id': typeof BooksIdRoute
  '/reviews/$id': typeof StaffReviewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/o_nas': typeof O_nasRoute
  '/users': typeof AdminUsersRoute
  '/my-reservations': typeof ProtectedMyReservationsRoute
  '/profile': typeof ProtectedProfileRoute
  '/wishlist': typeof ProtectedWishlistRoute
  '/authors': typeof StaffAuthorsRoute
  '/books_adm': typeof StaffBooks_admRoute
  '/feedbacks': typeof StaffFeedbacksRoute
  '/genres': typeof StaffGenresRoute
  '/new_newsletter': typeof StaffNew_newsletterRoute
  '/newsletter': typeof StaffNewsletterRoute
  '/publishers': typeof StaffPublishersRoute
  '/reservations': typeof StaffReservationsRoute
  '/reviews': typeof StaffReviewsRouteWithChildren
  '/books/$id': typeof BooksIdRoute
  '/reviews/$id': typeof StaffReviewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_staff': typeof StaffRouteWithChildren
  '/o_nas': typeof O_nasRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_protected/my-reservations': typeof ProtectedMyReservationsRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/wishlist': typeof ProtectedWishlistRoute
  '/_staff/authors': typeof StaffAuthorsRoute
  '/_staff/books_adm': typeof StaffBooks_admRoute
  '/_staff/feedbacks': typeof StaffFeedbacksRoute
  '/_staff/genres': typeof StaffGenresRoute
  '/_staff/new_newsletter': typeof StaffNew_newsletterRoute
  '/_staff/newsletter': typeof StaffNewsletterRoute
  '/_staff/publishers': typeof StaffPublishersRoute
  '/_staff/reservations': typeof StaffReservationsRoute
  '/_staff/reviews': typeof StaffReviewsRouteWithChildren
  '/books/$id': typeof BooksIdRoute
  '/_staff/reviews/$id': typeof StaffReviewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/o_nas'
    | '/users'
    | '/my-reservations'
    | '/profile'
    | '/wishlist'
    | '/authors'
    | '/books_adm'
    | '/feedbacks'
    | '/genres'
    | '/new_newsletter'
    | '/newsletter'
    | '/publishers'
    | '/reservations'
    | '/reviews'
    | '/books/$id'
    | '/reviews/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/o_nas'
    | '/users'
    | '/my-reservations'
    | '/profile'
    | '/wishlist'
    | '/authors'
    | '/books_adm'
    | '/feedbacks'
    | '/genres'
    | '/new_newsletter'
    | '/newsletter'
    | '/publishers'
    | '/reservations'
    | '/reviews'
    | '/books/$id'
    | '/reviews/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_protected'
    | '/_staff'
    | '/o_nas'
    | '/_admin/users'
    | '/_protected/my-reservations'
    | '/_protected/profile'
    | '/_protected/wishlist'
    | '/_staff/authors'
    | '/_staff/books_adm'
    | '/_staff/feedbacks'
    | '/_staff/genres'
    | '/_staff/new_newsletter'
    | '/_staff/newsletter'
    | '/_staff/publishers'
    | '/_staff/reservations'
    | '/_staff/reviews'
    | '/books/$id'
    | '/_staff/reviews/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  O_nasRoute: typeof O_nasRoute
  BooksIdRoute: typeof BooksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/o_nas': {
      id: '/o_nas'
      path: '/o_nas'
      fullPath: '/o_nas'
      preLoaderRoute: typeof O_nasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/reviews': {
      id: '/_staff/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof StaffReviewsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/reservations': {
      id: '/_staff/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof StaffReservationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/publishers': {
      id: '/_staff/publishers'
      path: '/publishers'
      fullPath: '/publishers'
      preLoaderRoute: typeof StaffPublishersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/newsletter': {
      id: '/_staff/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof StaffNewsletterRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/new_newsletter': {
      id: '/_staff/new_newsletter'
      path: '/new_newsletter'
      fullPath: '/new_newsletter'
      preLoaderRoute: typeof StaffNew_newsletterRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/genres': {
      id: '/_staff/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof StaffGenresRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/feedbacks': {
      id: '/_staff/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof StaffFeedbacksRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/books_adm': {
      id: '/_staff/books_adm'
      path: '/books_adm'
      fullPath: '/books_adm'
      preLoaderRoute: typeof StaffBooks_admRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/authors': {
      id: '/_staff/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof StaffAuthorsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_protected/wishlist': {
      id: '/_protected/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof ProtectedWishlistRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-reservations': {
      id: '/_protected/my-reservations'
      path: '/my-reservations'
      fullPath: '/my-reservations'
      preLoaderRoute: typeof ProtectedMyReservationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_staff/reviews/$id': {
      id: '/_staff/reviews/$id'
      path: '/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof StaffReviewsIdRouteImport
      parentRoute: typeof StaffReviewsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProtectedRouteChildren {
  ProtectedMyReservationsRoute: typeof ProtectedMyReservationsRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedWishlistRoute: typeof ProtectedWishlistRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedMyReservationsRoute: ProtectedMyReservationsRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedWishlistRoute: ProtectedWishlistRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface StaffReviewsRouteChildren {
  StaffReviewsIdRoute: typeof StaffReviewsIdRoute
}

const StaffReviewsRouteChildren: StaffReviewsRouteChildren = {
  StaffReviewsIdRoute: StaffReviewsIdRoute,
}

const StaffReviewsRouteWithChildren = StaffReviewsRoute._addFileChildren(
  StaffReviewsRouteChildren,
)

interface StaffRouteChildren {
  StaffAuthorsRoute: typeof StaffAuthorsRoute
  StaffBooks_admRoute: typeof StaffBooks_admRoute
  StaffFeedbacksRoute: typeof StaffFeedbacksRoute
  StaffGenresRoute: typeof StaffGenresRoute
  StaffNew_newsletterRoute: typeof StaffNew_newsletterRoute
  StaffNewsletterRoute: typeof StaffNewsletterRoute
  StaffPublishersRoute: typeof StaffPublishersRoute
  StaffReservationsRoute: typeof StaffReservationsRoute
  StaffReviewsRoute: typeof StaffReviewsRouteWithChildren
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAuthorsRoute: StaffAuthorsRoute,
  StaffBooks_admRoute: StaffBooks_admRoute,
  StaffFeedbacksRoute: StaffFeedbacksRoute,
  StaffGenresRoute: StaffGenresRoute,
  StaffNew_newsletterRoute: StaffNew_newsletterRoute,
  StaffNewsletterRoute: StaffNewsletterRoute,
  StaffPublishersRoute: StaffPublishersRoute,
  StaffReservationsRoute: StaffReservationsRoute,
  StaffReviewsRoute: StaffReviewsRouteWithChildren,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  O_nasRoute: O_nasRoute,
  BooksIdRoute: BooksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
